### PR TITLE
Merging Katrin's changes

### PR DESCRIPTION
**Pull request by kariljordan**

### CODE REVIEW

**Review by fmichonneau — CHANGES_REQUESTED** [review]
please don't include the packrat directory in the pull request. Thanks!

**Comment by kariljordan** [comment]
@fmichonneau I don't know what that means or how to fix it, but @katrintirok and I are meeting in 30 minutes so she can help!

**Comment by katrintirok** [comment]
I added the packrat folder to .gitignore, doesn't show up in the pull request yet though.

**Comment by kariljordan** [comment]
Closing this PR as @katrintirok will reorganize her files and submit a PR.

**Pull request closed without merging**
